# Generated by Django 4.1 on 2022-08-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(verbose_name='비밀번호'),
        ),
    ]
