# Generated by Django 4.1 on 2022-08-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='level',
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.TextField(null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='휴대폰 번호'),
        ),
    ]
