# Generated by Django 4.1 on 2022-08-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='join',
        ),
    ]
