# Generated by Django 4.1 on 2022-08-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='together',
        ),
    ]
