# Generated by Django 4.1 on 2022-08-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_alter_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
