# Generated by Django 4.1 on 2022-08-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0007_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
