# Generated by Django 4.1 on 2022-08-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_link',
            field=models.TextField(null=True, verbose_name='구매페이지'),
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.TextField(null=True, verbose_name='수령장소'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='target',
            field=models.IntegerField(max_length=11, null=True, verbose_name='목표 인원'),
        ),
    ]
