# Generated by Django 4.1 on 2022-08-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_link',
            field=models.TextField(null=True, verbose_name='구매 페이지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='상품 설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
    ]
