# Generated by Django 4.1 on 2022-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_buy_link_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buy_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='place',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='target',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='재고'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='상품설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='Shoppingmall_Product',
        ),
    ]
