# Generated by Django 4.1 on 2022-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_buy_link_remove_product_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='buy_link',
            field=models.TextField(null=True, verbose_name='구매 페이지'),
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.TextField(null=True, verbose_name='수령 장소'),
        ),
        migrations.AddField(
            model_name='product',
            name='target',
            field=models.IntegerField(max_length=11, null=True, verbose_name='목표 인원'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='상품 설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
