# Generated by Django 4.1 on 2022-08-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='people',
            field=models.IntegerField(max_length=11, null=True, verbose_name='참여 인원'),
        ),
    ]
