# Generated by Django 4.1 on 2022-08-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='people',
            field=models.IntegerField(default=0, max_length=11, null=True, verbose_name='참여 인원'),
        ),
    ]
